version: '3.7'

# Define services
services:
  ubxlib_agent:
    image: nexus-de-bln.u-blox.net:18001/ubxlib_docker:latest
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 188:* rmw'
      - 'c 189:* rmw'
    environment:
      SSH_AUTH_SOCK: '/run/user/keyring/ssh'
      HOSTNAME: '$HOSTNAME'
      SDK_DIR: '/home/ubxlib/sdks'
    entrypoint: '/scripts/entrypoint.sh'
    command: '-b "$ENTRY_UBXLIB_BRANCH" -c "$ENTRY_COMMAND"'
    volumes:
      - './scripts:/scripts:ro'
      - '/dev:/dev'
      - '$HOST_AGENT_HOME_DIR:/home/ubxlib'
      - '$SSH_AUTH_SOCK:/run/user/keyring/ssh'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 17003:17003 # PyRPC
